### PR TITLE
Clean up spaces. One of them fixes XML parsing

### PR DESCRIPTION
**Pull request by marwin79**
Fixes mathewmeconry/TV7_EPG_Data#10

### CODE REVIEW

**Comment by rbkn** [comment]
Hi @marwin79 - it looks like there's an error in this fix - the space needs to be after the escaped quote to separate the parameters but it's currently inside the start parameter's quotes.

I created #33 to fix.

**Comment by mathewmeconry** [comment]
I guess we can close this pull request? @rbkn

**Comment by rbkn** [comment]
> I guess we can close this pull request? @rbkn

@mathewmeconry 
Yes, I think we can.  Also the #33 fix looks to have worked.

**Comment by mathewmeconry** [comment]
Already fixed with #33

**Pull request closed without merging**
