### PR TITLE
More channels/icons, plus other small changes

### PR DESCRIPTION
**Pull request by phof**
- Added 3 channels
- Added icons from teleboy.ch (matching 113 icons in total)
- Other small changes

### CODE REVIEW

**Comment by mathewmeconry** [comment]
Hi @phof 

Thanks a lot for the changes :)
Just some small wishes and questions before I merge:
1. Why did you remove rai1 and rai2 out of the teleboy matching?`
2. Please move the functionality for the icon download from teleboy into it's own file inside the icon_sources folder

**Comment by phof** [comment]
Hey @mathewmeconry!

> Why did you remove rai1 and rai2 out of the teleboy matching?

Good question — I need to get back to you on this one, it's likely I could map rai3 through tele so mapped all 3 channels from the same provider.

> Please move the functionality for the icon download from teleboy into it's own file inside the icon_sources folder

The teleboy icons are pulled while looping through the programs list (not via a separate API call), so I kept the function definition inside main.py. Still prefer moving it to its own file?

**Comment by mathewmeconry** [comment]
> Good question — I need to get back to you on this one, it's likely I could map rai3 through tele so mapped all 3 channels from the same provider.

I would be still great to get the data from both sources. The more the better

> The teleboy icons are pulled while looping through the programs list (not via a separate API call), so I kept the function definition inside main.py. Still prefer moving it to its own file?

Yep saw that. Please move it still to another file. Just for the structure purpose.

**Comment by mathewmeconry** [comment]
thanks for the changes :)
I'll test and merge them later today

**Comment by mathewmeconry** [comment]
Thanks for the changes. They work flawlessly 👍 
The dump with the new data will be in around 1 hour uploaded

**Comment by phof** [comment]
[OT] @mathewmeconry @nbarrientos Care to join me on gitter.im so we can chat about improvements/issues?

**Comment by mathewmeconry** [comment]
@phof
good idea. I created a server https://discord.gg/4FMXY3c

I'll add it to the readme in both repos when I'm back on a computer

**Pull request merged**
